---
title: "EICs"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: true
    number_sections: false
    toc_float: true
---

```{r settings, echo = FALSE, results = "hide", message = FALSE}
#' Define the path where we can find the mzML files:
MZML_PATH <- "C:/Users/mgarciaaloy/Documents/mzML/"
#if (!file.exists(MZML_PATH))
#    stop("Can not find the directory with the mzML files: ", MZML_PATH)
```

# Preliminaries
```{r, message=FALSE}
study <- "standards_dilution" # specify "internal_standards" OR 
                              #         "standards_dilution"
mixnum <- 11 # specify which MIX
polarity <- "NEG" # specify "POS" or "NEG"

library(xcms)
library(reshape2)
library(ggplot2)
library(RColorBrewer)

# Set up parallel processing using 3 cores
if (.Platform$OS.type == "unix") {
    register(bpstart(MulticoreParam(2)))
} else {
    register(bpstart(SnowParam(2)))
}
```

# Data import
In the file `XXXX_files.txt` there is the information regarding 
the injection sequence.
```{r}
injections <- read.table(paste0("data/", study, "_files.txt"), #import the file
                         sep = "\t", header = TRUE, as.is = TRUE)
myfiles <- injections$mzML # get file names
myfiles <- myfiles[grep(polarity, myfiles)]# select files names of our polarity
if(study == "standards_dilution"){
  (myfiles <- myfiles[grep(paste0("MIX ", mixnum, "[A-Z]"), myfiles)])
}
```

Get the information regarding the standards that are in the samples.
```{r}
std_info <- read.table(paste0("data/", study, ".txt"),
                      sep = "\t", header = TRUE, as.is = TRUE)
if(study == "internal_standards"){
  colnames(std_info) <- c("name", "molecular_weight", "POS", "NEG", "RT")
} else if(study == "standards_dilution"){
  colnames(std_info) <- c("mix", "name", "molecular_weight", "POS", "NEG", "RT")
}
std_info$name <- c(substring(std_info$name, 1, 33))
std_info <- std_info[!is.na(std_info[, grep(polarity, colnames(std_info))]),]
if(study == "standards_dilution"){
  std_info <- subset(std_info, mix == mixnum)
}
std_info
```

# EICs
```{r}
da = 0.01
RTd = 5
if(study == "internal_standards"){
  getPalette = colorRampPalette(brewer.pal(12, "Paired"))
} else if(study == "standards_dilution"){
  getPalette = colorRampPalette(brewer.pal(9, "YlOrRd"))
}
mycols = getPalette(length(myfiles))  
data <- readMSData(paste0(MZML_PATH, myfiles), mode = "onDisk")
for(i in 1:nrow(std_info)){
  
  chr = chromatogram(data, 
                mz = 
                  cbind(std_info[i, grep(polarity, colnames(std_info))] - da, 
                        std_info[i, grep(polarity, colnames(std_info))] + da),
                   aggregationFun = "max")
  
  cmpname <- gsub("L-", "", std_info$name[i])
  cmpname <- tolower(gsub(" .*", "", cmpname))
  
  if(study == "internal_standards"){ 
    filename <- paste0("plots/IS_", cmpname, "_", 
                       polarity, ".png")} else if(
                         study == "standards_dilution"){
                         if(mixnum < 10){
    filename <- paste0("plots/MIX_0", mixnum, "_", cmpname, "_", 
                       polarity, ".png") 
                         } else{
    filename <- paste0("plots/MIX_", mixnum, "_", cmpname, "_", 
                       polarity, ".png") 
                         }
                       }
  png(file = filename, units = "px", width = 3000, height = 1600, res = 300)
  
  par(mfrow=c(1,2))
  
  plot(chr, col=mycols, ylab="", main=std_info$name[i])
  abline(v=std_info$RT[i], lty=2)
  
  if(!is.na(std_info$RT[i])){
    plot(chr, col=mycols, ylab="",
         xlim=c(std_info$RT[i] - RTd, std_info$RT[i] + RTd))
    abline(v=std_info$RT[i], lty=2)
  }else{
    plot(chr, col=mycols, ylab="",
         xlim=c(rtime(chr[[length(chr)]])[
         which.max(intensity(chr[[length(chr)]]))] - RTd, 
         rtime(chr[[length(chr)]])[
         which.max(intensity(chr[[length(chr)]]))] + RTd))
    text(rtime(chr[[length(chr)]])[
         which.max(intensity(chr[[length(chr)]]))] - (RTd - 1), 
         intensity(chr[[length(chr)]])[
         which.max(intensity(chr[[length(chr)]]))] - (RTd - 1),
         "NOT RT")
  }
  
  
  dev.off()
}
```


