---
title: "Evaluation"
subtitle: "Internal Standards: Matrix effect"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: true
    number_sections: false
    toc_float: true
---

```{r include = FALSE}
knitr::opts_chunk$set(echo=TRUE)

startpoint <- Sys.time()
```

# Preliminaries
## Parameters
```{r}
polarity <- "POS" # specify "POS" or "NEG"
study <- "IS"     # specify "IS" or "QC"
dir.create(paste0("images/", study, "/", polarity, "/peak_shape"), 
           recursive = TRUE, showWarnings = FALSE)
dir.create(paste0("images/", study, "/", polarity, "/peak_chr"), 
           recursive = TRUE, showWarnings = FALSE)
```

## Libraries
```{r, message=FALSE}
library(xcms)
library(RColorBrewer)
```


## Data import
```{r}
load(paste0("filter_group_", study, "_", polarity, ".Rdata"))
```

# Output
## Peak shapes
```{r, eval = TRUE}
for(i in seq(nrow(tb.ann))
){
  feat.i <- feat_filter[feat_filter$cmp == tb.ann$C[i], ]
  if(nrow(feat.i) > 1){
    ft.i <- rownames(feat.i)[which.max(feat.i$int)]
    xdata_n <- 
      filterFile(raw_data, order(data_imp[, ft.i], 
                                 decreasing=TRUE)[1:3][1])
    if(grepl("Carnitine", feat.i$compound[which.max(feat.i$int)])){
      rtr <- c(feat.i$rtmed[which.max(feat.i$int)] + 60 * c(-1,1))
    } else{
      rtr <- c(feat.i$rtmed[which.max(feat.i$int)] + 30 * c(-1,1))
    }
    chr <- chromatogram(
      xdata_n, 
      mz = c(feat.i$mzmed[which.max(feat.i$int)] + 0.1 * c(-1,1)),
      rt = rtr)
    mz.vals <- feat.i$mzmed
    mz.vals <- mz.vals[!mz.vals %in% feat.i$mzmed[which.max(feat.i$int)]]
    mz.vals <- mz.vals[order(mz.vals)]
    chr2 <- list()
    for(k in seq(length(mz.vals))){
      chr2[[k]] <- chromatogram(xdata_n, aggregationFun = "max",
                                mz = c(mz.vals[k] + 0.01 * c(-1, 1)), 
                                rt = rtr)
    }
    mycolors <- colorRampPalette(brewer.pal(9, "Set1"))(length(mz.vals))
    
    cmpname <- feat.i$compound[which.max(feat.i$int)]
    if(!grepl("X", cmpname)){
      cmpname <- tolower(cmpname)
      cmpname <- sub(" .*", "", cmpname)
      cmpname <- gsub("l-", "", cmpname)
      cmpname <- paste("IS", cmpname, sep = "_")
    }
    filename <- paste0("images/", study, "/", polarity, "/peak_shape/", 
                       cmpname, ".png")
    png(file = filename, width = 1000, height = 500)
    plot(
      rtime(chr@.Data[[1]]), 
      (intensity(chr@.Data[[1]]) / 
         max(intensity(chr@.Data[[1]]), na.rm = T))*100, type="l", 
      xlab = "Retention Time (seconds)", ylab = "Relative intensity",
      xlim = rtr, 
      main = paste(feat.i$compound[which.max(feat.i$int)], 
                   "\n", xdata$sample[order(data_imp[, ft.i], 
                                            decreasing=TRUE)[1:3][1]]))
    
    for(k in seq(length(mz.vals))){
      lines(rtime(chr2[[k]]@.Data[[1]]), 
            (intensity(chr2[[k]]@.Data[[1]]) / 
               max(intensity(chr2[[k]]@.Data[[1]]), na.rm=T))*100, 
            col = mycolors[k])
    }
    legend("topright", 
           legend = c(round(feat.i$mzmed[which.max(feat.i$int)], 4), 
                      round(mz.vals, 4)), 
           col = c("black", mycolors), pch = 16, ncol = 1)
    
    dev.off()
  }
}
```

## Peak along chromatogram
```{r}
for(i in seq(nrow(tb.ann))
){
  feat.i <- feat_filter[feat_filter$cmp == tb.ann$C[i], ]
  ft.i <- rownames(feat.i)[which.max(feat.i$int)]
  mz.i <- feat.i$mzmed[which.max(feat.i$int)]
  chrs <- list()
  for(k in seq(3)){
    xdata_n <- 
      filterFile(raw_data, 
                 order(data_imp[, ft.i], decreasing=TRUE)[1:3][k])
    chrs[[k]] <- chromatogram(xdata_n, aggregationFun = "max",
                              mz = c(mz.i + 0.01 * c(-1, 1)))
  }
  
  cmpname <- feat.i$compound[which.max(feat.i$int)]
  if(!grepl("X", cmpname)){
    cmpname <- tolower(cmpname)
    cmpname <- sub(" .*", "", cmpname)
    cmpname <- gsub("l-", "", cmpname)
    cmpname <- paste("IS", cmpname, sep = "_")
  }
  filename <- paste0("images/", study, "/", polarity, "/peak_chr/", 
                     cmpname, ".png")
  png(file = filename, width = 1500, height = 500)
  par(mfrow = c(1,3), mar = c(0.5,0,2,0.5))
  k = 1
  plot(chrs[[k]], yaxt = "none", xaxt = "none",
       main = 
         xdata$sample[order(data_imp[, ft.i], decreasing=TRUE)[1:3][k]])
  k = 2
  plot(chrs[[k]], yaxt = "none", xaxt = "none", 
       main = 
         xdata$sample[order(data_imp[, ft.i], decreasing=TRUE)[1:3][k]])
  k = 3
  plot(chrs[[k]], yaxt = "none", xaxt = "none", 
       main = 
         xdata$sample[order(data_imp[, ft.i], decreasing=TRUE)[1:3][k]])
  dev.off()
}
```


# Session information
```{r}
Sys.time()-startpoint

devtools::session_info()
```

