---
title: "Formula finder"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: true
    number_sections: false
    toc_float: true
---

```{r startpoint, include = FALSE}
startpoint <- Sys.time()
```

# Preliminaries

```{r preliminaries}
library(MetaboCoreUtils)
library(Rdisop)
library(RColorBrewer)
library(kableExtra)

load("isotopic_patterns_tables.RData")
rm(startpoint)
samples <- ls()
startpoint <- Sys.time()

std_info <- read.table(
  "../data/standards_dilution.txt",
  sep = "\t", header = TRUE, as.is = TRUE)
std_info <- std_info[, c("mix", "name", "abbreviation", "formula",
                         "POS", "NEG", "quality_POS", "quality_NEG")]
idx <- which(std_info$name == "3-Hydroxy-DL-kynurenine" & 
               std_info$mix == 17)
std_info <- std_info[-idx, ]
std_info <- std_info[-which(std_info$name == "Eplerone"), ]
idx <- which(std_info$name == "Glycerophospho-inositol")
std_info <- std_info[-idx, ]
std_info$formula[std_info$abbreviation == 
                   "chlorotrifluoromethylpyrindol"] <- "C6H3NOClF3"
std_info$formula[std_info$abbreviation == 
                   "dichlorohydroxypyridine"] <- "C5H3NOCl2"
std_info$formula[std_info$abbreviation == 
                   "trichloropyrinidol"] <- "C5H2NOCl3"

std_info <- std_info[!is.na(std_info$quality_POS), ]
std_info <- std_info[std_info$quality_POS == "0_perfect" | 
                       std_info$quality_POS == "1_good", ]
std_info <- std_info[std_info$quality_NEG == "0_perfect" | 
                       std_info$quality_NEG == "1_good", ]
std_info <- std_info[std_info$POS == "[M+H]+" & 
                       std_info$NEG == "[M-H]-", ]
std_info$mzneut <- NA
for(i in 1:nrow(std_info)){
  std_info$mzneut[i] <- 
    getMolecule(as.character(std_info$formula[i]))$exactmass
}
tmp <- lapply(as.character(std_info$formula), countElements)
tmp <- do.call(dplyr::bind_rows, tmp)
tmp[is.na(tmp)] <- 0
std_info <- cbind(std_info, tmp)
```


# Formula finder

```{r main-code}
for(y in 22:length(samples)){
  
  tmp <- get(samples[y])
  
  formula_finder <- matrix(nrow=nrow(std_info), ncol = 7)
  rownames(formula_finder) <- std_info$abbreviation
  colnames(formula_finder) <- c("start", "thr_filters", "A1_filter", 
                                "C1_filter", "A2_filter", "rank", "rankp")
  
  for(z in 1:nrow(std_info)
  ){
    if(!is.na(tmp$mz1[z])){
      mzval <- tmp$mz1[z] - 1.007276
      if(mzval <= 250){myppm <- 40
      } else if(mzval > 250 & mzval < 600){myppm <- 25
      } else if(mzval >= 600){myppm<- 15}
      if(tmp$i1[z] < 5e5){
        myerror_A1 <- 0.4
        myerror_A2 <- 2
      } else {
        myerror_A1 <- 1.5
        myerror_A2 <- 5
      }
      
      #tmp$mz1[z]
      if(grepl("Cl", std_info$formula[z])){
        tmp.frm1 <- data.frame(
          formula = decomposeMass(mzval, ppm = myppm,
                                  elements = initializeElements(
                                    c("C", "H", "N", "O", 
                                      "P", "S", "Cl", "F"))
          )$formula) 
      } else{
        tmp.frm1 <- data.frame(
          formula = decomposeMass(mzval, ppm = myppm)$formula) 
      }
      tmp.frm1 <- cbind(
        tmp.frm1, 
        do.call(dplyr::bind_rows, 
                lapply(as.character(tmp.frm1$formula), countElements)))
      tmp.frm1[is.na(tmp.frm1)] <- 0
      
      ### Theoretical rules
      tmp.frm1$H_rule <- tmp.frm1$H <= tmp.frm1$C*2 + tmp.frm1$N + 2
      tmp.frm1$N_rule <- tmp.frm1$N %% 2 == round(mzval) %% 2
      tmp.frm1$RPU_rule <- # RPU <- (C+Si) - (H+Cl+Fl+I)/2 + (N+P)/2 + 1
        (tmp.frm1$C - 
           ((tmp.frm1$H)/2) + 
           ((tmp.frm1$N + tmp.frm1$P)/2) + 1)  >= 0 
      
      ### Experimental rules
      tmp.frm1$formula <- as.character(tmp.frm1$formula)
      tmp.frm1$A1 <- NA
      tmp.frm1$A2 <- NA
      for(i in 1:nrow(tmp.frm1)){
        tmpx <- getMolecule(tmp.frm1$formula[i])$isotopes[[1]]
        tmp.frm1$A1[i] <- (tmpx[2,2]/tmpx[2,1])*100
        tmp.frm1$A2[i] <- (tmpx[2,3]/tmpx[2,1])*100
      }
      
      if(!is.na(tmp$i2[z])){
        tmp.A1 <- (tmp$i2[z] / tmp$i1[z]) * 100
        (A1_range <- tmp.A1 + (tmp.A1 * myerror_A1 * c(-1, 1)))
        tmp.frm1$A1_rule <- tmp.frm1$A1 >= A1_range[1] & 
          tmp.frm1$A1 <= A1_range[2]
        
        tmp.frm1$C_cntrb <- (tmp.frm1$C * 1.07) / tmp.frm1$A1
        tmp.frm1$C_thr <- (tmp.A1*tmp.frm1$C_cntrb)/1.07
        tmp.frm1$C_thr_min <- tmp.frm1$C_thr - (tmp.frm1$C_thr * myerror_A1)
        tmp.frm1$C_thr_max <- tmp.frm1$C_thr + (tmp.frm1$C_thr * myerror_A1)
        tmp.frm1$C_rule <- 
          tmp.frm1$C >= tmp.frm1$C_thr_min & 
          tmp.frm1$C <= tmp.frm1$C_thr_max
      }else { # end if A+1 is NOT missing 
        tmp.frm1$A1_rule <- TRUE
        tmp.frm1$C_rule <- TRUE
      } 
      
      if(!is.na(tmp$i3[z])){
        tmp.A2 <- (tmp$i3[z] / tmp$i1[z]) * 100
        (A2_range <- tmp.A2 + (tmp.A2 * myerror_A2 * c(-1, 1)))
        if(A2_range[1] < 0){A2_range[1] <- 0}
        tmp.frm1$A2_rule <- 
          tmp.frm1$A2 >= A2_range[1] & tmp.frm1$A2 <= A2_range[2]
      } else { # end if A+2 is NOT missing 
        tmp.frm1$A2_rule <- TRUE
      } 
      
      formula_finder[z, "start"] <- nrow(tmp.frm1)
      formula_finder[z, "thr_filters"] <- 
        sum(tmp.frm1$H_rule & tmp.frm1$N_rule & tmp.frm1$RPU_rule)
      formula_finder[z, "A1_filter"] <- 
        sum(tmp.frm1$H_rule & tmp.frm1$N_rule & tmp.frm1$RPU_rule & 
              tmp.frm1$A1_rule)
      formula_finder[z, "C1_filter"] <- 
        sum(tmp.frm1$H_rule & tmp.frm1$N_rule & tmp.frm1$RPU_rule & 
              tmp.frm1$A1_rule & tmp.frm1$C_rule)
      formula_finder[z, "A2_filter"] <- 
        sum(tmp.frm1$H_rule & tmp.frm1$N_rule & tmp.frm1$RPU_rule & 
              tmp.frm1$A1_rule & tmp.frm1$C_rule & tmp.frm1$A2_rule)
      
      tmpx <- 
        tmp.frm1[tmp.frm1$H_rule & tmp.frm1$N_rule & tmp.frm1$RPU_rule & 
                   tmp.frm1$A1_rule & tmp.frm1$C_rule & tmp.frm1$A2_rule,]
      
      if(nrow(tmpx) > 0){
        tmpx$A1x <- abs(tmpx$A1 - tmp.A1)
        if(!is.na(tmp$i3[z])){tmpx$A2x <- abs(tmpx$A2 - tmp.A2)} else {
          tmpx$A2x <- 0}
        tmpx$A <- NA
        #tmpx$Aw <- NA
        for(i in 1:nrow(tmpx)){
          tmpx$A[i] <- mean(c(tmpx$A1x[i], tmpx$A2x[i]))
          #tmpx$Aw[i] <- weighted.mean(c(tmpx$A1x[i], tmpx$A2x[i]), c(2,1))
        }
        tmpx <- tmpx[order(tmpx$A),]
        #tmpx$H <- tmpx$H - 1
        tmpx$fml <- NA
        tmpx$A1p <- NA
        tmpx$A2p <- NA
        tmpx$Ap <- NA
        for(i in 1:nrow(tmpx)){
          tmpx$fml[i] <- pasteElements(
            tmpx[i, 2:(which(colnames(tmpx) == "H_rule") - 1)])
          tmpx$A1p[i] <- abs(100 - ((tmp.A1*100)/tmpx$A1[i]))
          if(!is.na(tmp$i3[z])){
            tmpx$A2p[i] <- abs(100 - ((tmp.A2*100)/tmpx$A2[i]))
          } else {tmpx$A2p[i] <- 0}
          tmpx$Ap[i] <- mean(c(tmpx$A1p[i], tmpx$A2p[i]))
        }
        tmpx <- tmpx[order(tmpx$A), ]
        formula_finder[z, "rank"] <- which(tmpx$fml == std_info$formula[z])
        tmpx <- tmpx[order(tmpx$Ap),]
        formula_finder[z, "rankp"] <- which(tmpx$fml ==std_info$formula[z])
      }# end if nrow(tmpx) > 0
    } # close if A+0 is NOT missing
    save.image("tmp.RData")
  }
  assign(paste0(samples[y], "_formfind"), formula_finder)
} # end sample Y

rm(tmp, tmp.frm1, tmpx, A1_range, A2_range, i, idx, 
   myerror_A1, myerror_A2, myppm, mzval, tmp.A1, tmp.A2, z)
```


# Table

```{r}
formula_finder <- c()
for(i in 22:length(samples)){
  formula_finder[[i-21]] <- get(paste0(samples[i], "_formfind"))
  names(formula_finder)[[i-21]] <- samples[i]
}

formfind <-  matrix(nrow=nrow(std_info), ncol = 7)
rownames(formfind) <- std_info$abbreviation
colnames(formfind) <- c("start", "thr_filters", "A1_filter", 
                        "C1_filter", "A2_filter", "rank", "rankp")

for(i in 1:nrow(formfind)){
  for(j in 1:ncol(formfind)){
    tmp <- c()
    for(k in 1:length(formula_finder)){
      tmp <- c(tmp, formula_finder[[k]][i,j])
    }
    if(is.na(tmp[1])){
      formfind[i, j] <- NA
    } else if(range(tmp)[1] == range(tmp)[2]){
      formfind[i, j] <- range(tmp)[1]
    } else {
      formfind[i, j] <- paste(range(tmp)[1], range(tmp)[2], sep="-")
    }
  } # close parameter "j"
} # end std "i"

formfind %>%
  kable() %>%
  kable_styling()

save.image("formfind_data.RData")
```


# Session information

```{r session}
Sys.time()-startpoint

devtools::session_info()
```
